spring:
  profiles:
    active: dev  # Default to 'dev' profile for local development
  datasource:
    # Placeholder, actual values will be set in dev/prod specific files
    username: ${DB_USERNAME}  # Environment variable placeholder
    password: ${DB_PASSWORD}  # Environment variable placeholder
    driver-class-name: ${DB_DRIVER}  # Environment variable placeholder
  jpa:
    hibernate:
      ddl-auto: update  # Use 'validate' in prod to avoid accidental changes
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080  # The port the application will run on
