#For PostgreSQL (Production Database):

spring.config.activate.on-profile: prod

spring.datasource:
  url: jdbc:postgresql://prod-db-server:5432/expensedb?currentSchema=expense
  username: expense_user
  password: expense_password
  driver-class-name: org.postgresql.Driver

spring.jpa.hibernate:
  ddl-auto: validate

spring.flyway:
  enabled: true
  locations: classpath:db/migration

server:
  port: 8080



#For Oracle (Production Database):
#
#spring.config.activate.on-profile: prod
#
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@prod-db-server:1521:expensedb
#    username: tarif
#    password: tarif@123
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: validate  # Ensures schema is validated but not modified
#    open-in-view: false
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
